window.BT = window.BT || {};
window.BT.v3tilesWP  = window.BT.v3tilesWP || {};
window.BT.v3tilesWP.lang = window.BT.v3tilesWP.lang || {};
window.BT.v3tilesWP.lang['en-us'] = {
    "regional_settings": {
        "browser_not_support": "Your browser does not support the video tag.",
        "loading_data": "loading tile data...",
        "no_results_found": "no results found",
        "loading_twitter": "loading twitter feed...",
        "no_tweets": "no tweets to show",
        "loading_weather": "loading weather data..."
    },
    "webpart_toolbar": {
        "webpart_name": "Tiles",
        "loading_twitter": "Loading Twitter Feed",
        "loading_weather": "Loading Weather Feed",
        "new_entry": "Create new Tile",
        "properties": "Web Part Properties",
        "manage": "Manage Tiles",
        "list": "Tiles List",
        "version": "Version"
    },
    "webpart_new_item": {
        "modal_heading": "Create new Tile",
        "tile_settings_heading": "Tile Settings",
        "tile_background_color": "Tile Background Color",
        "tile_shape_label": "Tile Shape",
        "set_color_transparency": "Set the color transparency",
        "content": "Content",
        "text_color_label": "Text Color",
        "tile_order_label": "Tile Order",
        "tile_status_label": "Tile Status",
        "tile_load_lists": "Load lists",
        "tile_status_checkbox": "Active",
        "tile_type_label": "Tile Type",
        "tile_list_name": "List Name",
        "tile_type_option_plain": "Plain",
        "tile_type_option_link": "Link",
        "tile_type_option_document": "Document",
        "tile_type_option_document_library": "Document Library",
        "tile_type_option_video": "Video",
        "tile_type_option_smart_tile": "Smart Tile",
        "tile_type_option_twitter_feed": "Twitter Feed",
        "tile_type_option_weather": "Weather",
        "tile_type_option_powerbi": "Power BI",
        "target_users_label": "Target Users",
        "target_users_warning": "Page caching is enabled. Tiles with target users won't be displayed.",
        "front_tile_settings_heading": "Front Tile Settings",
        "tile_background_label": "Tile Background",
        "tile_background_option_color": "Color",
        "tile_background_option_image": "Image",
        "tile_background_placeholder": "e.g. #000000",
        "tile_background_transparency": "Transparency",
        "tile_background_tip": "Choose between a background color or a background image.",
        "caption_position_label": "Caption positions",
        "caption_position_top": "Top",
        "caption_position_center": "Center",
        "caption_position_bottom": "Bottom",
        "caption_content_info": "We support Markdown. Check syntax rules ",
        "caption_content_info_here": "here",
        "caption_background_label": "Caption Background",
        "caption_background_placeholder": "e.g. #000000",
        "caption_background_transparency": "Transparency",
        "back_tile_settings_heading": "Back Tile Settings",
        "back_tile_background_label": "Back Tile Background",
        "back_tile_background_option_color": "Color",
        "back_tile_background_option_image": "Image",
        "back_tile_background_color_placeholder": "e.g. #000000",
        "back_tile_background_image_placeholder": "Background Image URL",
        "back_tile_background_transparency": "Transparency",
        "caption_position_option_left": "Left",
        "caption_position_option_center": "Center",
        "caption_position_option_right": "Right",
        "content_info": "We support Markdown. Check syntax rules here",
        "content_here": "here",
        "flip_settings_heading": "Animation Settings",
        "flip_animation_label": "Flip Animation",
        "flip_animation_option_none": "None",
        "flip_animation_option_flip": "Flip",
        "flip_animation_option_slide_up": "Slide Up",
        "flip_animation_option_slide_down": "Slide Down",
        "auto_flip_label": "Animation Interval",
        "auto_flip_placeholder": "Interval",
        "auto_flip_seconds": "seconds",
        "setup_link": "Setup a link",
        "clickable_link": "Clickable Link",
        "type_url_page": "Type the url to a page",
        "open_new_window": "Open link in new window",
        "connect_document": "Connect to your Document",
        "document_url": "Type the document url",
        "title_label": "Title",
        "type_doc_label": "Type the document title",
        "connect_doc_library": "Connect to your Document Library",
        "doc_library_url": "Type the document library url",
        "doc_library_title": "Type the document library title",
        "connect_video": "Connect to a Video",
        "doc_video_url": "Type the document video url",
        "type_video_title": "Type the video title",
        "connect_dashboard": "Connect to a Power BI Dashboard",
        "dashboard_url": "Type the dashboard url",
        "dashboard_only": "Public dashboards only",
        "settings_tile": "Twitter Tile Settings",
        "widget_id": "Widget ID",
        "info_widget_id": "You can find more information about the Widget ID in the user guide.",
        "number_tweets": "Number of tweets",
        "options_label": "Options",
        "show_date": "Show date",
        "show_user": "Show user",
        "action_buttons": "Show action buttons",
        "weather_settings": "Weather Tile Settings",
        "default_location": "Default Location",
        "city_state_country": "City, State or Country",
        "dynamic_location": "Dynamic Location",
        "detect_location": "Detect user location",
        "measurements": "Measurements",
        "forecast": "Forecast",
        "daily": "Daily",
        "weekly": "Weekly",
        "btn_cancel": "Cancel",
        "btn_preview": "Preview",
        "btn_preview_end": "Continue Editing",
        "btn_publish": "Publish",
        "btn_save": "Save",
        "btn_save_draft": "Save as Draft",
        "btn_review_tooltip": "Saved for review and will be published by a reviewer.",
        "btn_review": "Submit for Review",
        "btn_saving": "Saving...",
        "btn_publish_tooltip": "Publish the tile. Will appear on the page to all users.",
		"tile_status_published": "published",
		"tile_status_draft": "draft",
		"tile_status_revision": "waiting approval"
    },
    "webpart_properties": {
        "modal_heading": "Edit Tile",
        "options_heading": "Tiles Options",
        "settings_source_label": "Settings Source",
        "settings_source_nothing": "Nothing Selected",
        "settings_source_copy": "Copy",
        "settings_source_copy_success": "Properties copied successfully.",
        "tiles_list_heading": "Tiles List",
        "list_url_label": "List Url",
        "list_url_placeholder": "e.g. https://contoso.sharepoint.com/Lists/Tiles/AllItems.aspx",
        "data_source": "Connect to a Data Source",
        "add_list": "Add List",
        "sorting_options": "Item Sorting Options",
        "order_by": "Order by",
        "add_order_by": "Add Order by",
        "grid_settings_headings": "Grid Settings",
        "max_tiles_label": "Max Tiles Per Row",
        "max_tiles_flexible": "Flexible",
        "tiles_spacing_label": "Tiles Spacing (px)",
        "tiles_spacing_option_0": "Zero",
        "tiles_spacing_option_5": "Five",
        "tiles_spacing_option_10": "Ten",
        "tiles_spacing_option_20": "Twenty",
        "tiles_alignment_label": "Tiles Alignment",
        "tiles_alignment_option_grid": "Grid",
        "tiles_alignment_option_wall": "Wall",
        "grid_size_label": "Grid Size",
        "grid_size_checkbox": "Locked",
        "minimum_size_label": "Minimum Tile Size",
        "minimum_tile_option_100": "Extra Tiny (100px)",
        "minimum_tile_option_150": "Tiny (150px)",
        "minimum_tile_option_175": "Small (175px)",
        "minimum_tile_option_200": "Medium (200px)",
        "minimum_tile_option_250": "Large (250px)",
        "advanced_options_heading": "Advanced Options",
        "caching_label": "Caching",
        "caching_option_nocaching": "No Caching (Updates Every Page Load)",
        "caching_option_page": "Page Caching (updates when web part is saved)",
        "caching_option_localstorage": "Local Storage Caching (updates every 30 minutes)",
        "caching_add_new_warning": "With this option enabled, the web part will not update until the properties are saved or you add a new item using the web part's forms.",
        "caching_user_targetting_warning": "Tiles with user targetting will not be displayed using this option.",
        "caching_limited_space_warning": "Browsers have limited space available for local storage. Other web parts or scripts resorting to LocalStorage may lose functionality when it becomes full.",
        "language_label": "Language",
        "some_texts_warning": "Some texts may not be updated until the page gets refreshed.",
        "chrome_appearance": "Web Part Appearance",
        "chrome_type_label": "Chrome Type",
        "chrome_type_option_default": "Default",
        "chrome_type_option_none": "None",
        "chrome_type_option_title_border": "Title and Border",
        "chrome_type_option_title": "Title Only",
        "chrome_type_option_border": "Border Only",
        "webpart_title_label": "BindTuning Quick Links",
        "webpart_title_default_text": "BindTuning Calendar",
        "webpart_url_label": "Web Part URL",
        "webpart_tooltip_label": "Web Part Tooltip",
        "webpart_tooltip_default_text": "Display favorite links so they show up right where you need them, visually enriched with colourful and distinctive icons, using targeting options that suit your needs.",
        "rtl_label": "Right to Left",
        "rtl_checkbox_label": "Active",
        "publishing_workflow_heading": "Publishing Workflow",
        "publishing_workflow_checkbox": "Enable Publishing Workflow",
        "target_users_label": "Approved Reviewers",
        "weather_settings": "Weather Settings",
        "provider_label": "Provider",
        "provider_option_free": "free",
        "api_key_label": "API Key",
        "api_key_placeholder": "API key of the selected provider",
        "api_key_tip": "To get an API Key for the selected provider, create an account ",
        "api_key_tip_here": "here",
		"webpart_messages" : "Web Part Messages",
        "calendar_webpart_errors_label": "Web Part errors",
        "calendar_webpart_errors_option_edit": "Show In Edit Mode Only",
        "calendar_webpart_errors_option_always": "Always Show",
        "calendar_webpart_errors_option_never": "Never Show",
        "btn_copy": "Copy Properties",
        "btn_cancel": "Cancel",
        "btn_save": "Save",
		"btn_saving": "Saving...",
        "sort_ascending": "Ascending",
        "sort_descending": "Descending"
    },
    "webpart_list": {
        "modal_heading": "Tiles List",
        "order": "Order",
        "tile_type": "Tile Type",
        "visible": "Visible",
        "list_name": "List Name",
        "background": "Background",
        "caption": "Caption",
        "status": "Status",
        "delete_alert": "Are you sure you want to remove this tile?",
        "delete_success": "Tile was successfully deleted",
        "no_entries": "No entries to display",
        "edit_tooltip": "Edit",
        "delete_tooltip": "Delete",
        "publish_tooltip": "Publish",
        "load_list": "Load List"
    },
    "webpart_messages": {
        "wp_not_configured": "This Web Part is not fully configured.",
        "cant_save": "Can\'t save properties before saving or deleting this field.",
        "connect_to_list": "Open the Web Part properties and connect it to a list.",
        "not_provided": "A source list was not provided",
        "connect_smart_slider": "Smart sliders retrieve information from your SharePoint lists. Connect it to one of them to see their content displayed here",
        "localstorage_full": "BT WebParts: Localstorage is full and the web part was not succesfully cached.",
        "couldnt_load_lists": "It seems we couldn't load the provided lists. Please make sure you typed the correct URLs.",
        "check_user_guide": "If you have any questions on how to implement the web part, please check the user guide.",
        "list_label": "List(s): ",
		"list_empty": "Your list is empty. Please add data to your list.",
        "certain_groups": "Visible to certain users or groups",
        "not_referencing": "Oops. This tile is not referencing any documents.",
        "please_check": "Please check if you have added a valid url by editing this tile in edit mode.",
        "provided_view": "Provided view cannot be null",
        "waiting_approval": "This web part have Tiles waiting for approval.",
        "show_details": "Show details...",
        "hide_details": "Hide details...",
        "failed_to_save": "Failed to save properties: ",
        "failed_to_get": "Failed to get properties from webpart: ",
        "page_checked_in": "Page is checked in! Check Out the page and save the web part for these changes to take effect.",
        "tiles_with_targetting": "Tiles with user targetting will not be displayed using this option.",
        "wp_properties_saved": "Web part properties saved successfully",
        "something_wrong": "Oops, something went wrong:",
        "preview_mode": "Preview Mode",
        "tile_successfuly_saved": "Tile successfuly saved",
        "no_permission": "Oops, you don't have permission to make this change.",
        "slide_updated": "Tile was successfuly updated.",
        "sure_want_remove": "Are you sure you want to remove this tile?",
        "failed_delete": "Failed to delete the tile:",
        "failed_retrieve_data": "Failed to retrieve tile data:",
        "tile_published": "Tile was successfully published",
        "failed_publish": "Failed to publish the tile:",
        "site_not_found": "Site not found.",
        "no_filters": "No Filters",
        "filtering_options": "Filtering Options:",
        "select_view": "Select a View",
        "no_lists": "No Lists",
        "select_list": "Select List",
        "couldnt_load_lists_corrupted": "Couldn't load lists from site. Make sure there are no corrupted lists and apps on the site."
    }
};
